USE WAREHOUSE COMPUTE_WH;
USE SCHEMA PUBLIC;

create or replace TABLE SALES_DATA (
	SALES_ID VARCHAR(38),
	CUSTOMER_NAME VARCHAR(38),
	TRANSACTION_ID VARCHAR(38),
	TRANSACTION_DATE VARCHAR(29),
	AMOUNT VARCHAR(20)
);
