USE WAREHOUSE COMPUTE_WH;
USE SCHEMA PUBLIC;

create or replace TABLE Transactions (
	SALES_ID NUMBER(38,0),
	CUSTOMER_NAME VARCHAR(16777216),
	TRANSACTION_ID NUMBER(38,0),
	TRANSACTION_DATE DATE,
	AMOUNT FLOAT
);
